when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.7-jdk17-alpine@sha256:776ba728f7af4f89cd5ed534792daf77c95bca310196ddd46c864af4d7120649
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
