when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.10-jdk17-alpine@sha256:490f964332c20b66bfd293dad6bb06ec16230ee1b13a4e91e668e2741b3d3771
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
