when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.8-jdk17-alpine@sha256:bbb264cb9b7aca0213f849f9b2f4989edea4b32fe85f026f3852f2f956d08fd4
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
