when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.7-jdk17-alpine@sha256:fb89afb77148e3dba457ff30787436b8dcf578372e9275b3c4d1c49ecb1358b0
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
