when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.13-jdk17-alpine@sha256:1a505a603ab40e4eb5385eae3c257576a21af66b5f709a44800f3568293bd981
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
