when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.10-jdk17-alpine@sha256:6e9712ecc0ead54b3afd661d2356b74adda9fdca8a8de9ace068f53f7c9a200a
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
